### ISSUE TITLE
Cleanup of shoot leftover resources

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#5173]
**How to categorize this issue?**

/area control-plane-migration
/kind enhancement

**What would you like to be added**:
We should introduce a cleanup mechanism for leftover resources in a Seed cluster that once contained the control plane of a Shoot cluster that are no longer needed since the Shoot cluster has been meanwhile force restored to a different seed (see #5123), or force deleted. Such resources include the shoot namespace (and all resources in it), the shoot `BackupEntry` resource, and the `Cluster` resource.

**Why is this needed**:
Without such a mechanism, leftover resources would remain in the seed cluster indefinitely and consume CPU and memory resources until manually removed.

**Comment by stoyanr** [comment]
Basically what we need is a controller that implements cleanup logic similar to the following script: https://github.com/plkokanov/control-plane-cleanup/blob/master/migrate-resources.sh. We should clarify what resource such a controller reconciles and uses in order to report the progress and errors of a cleanup operation.

It should be noted that the original `Shoot` resource can't be used for this purpose, as it's either already scheduled on a different seed (and is therefore reconciled by its `gardenlet`), or doesn't exist at all. For example, one could easily imagine a situation in which the `Shoot` has been force restored to a different seed and then deleted, before the controller responsible for deleting the leftover resources had the chance to do its job.

The possible alternatives are:
* No resource. The controller detects the need for cleanup by detecting the leftover resources in the seed directly, e.g. a `Cluster` or a namespace resource in a seed that the corresponding `Shoot` is no longer scheduled on (or does not even exist). It does not report progress and errors in a status, only via log messages and events associated with the existing resources. The main disadvantages of this approach are:
    - Progress and errors are not reported in a status, and therefore harder to track and monitor, or even be aware that a cleanup is happening (and possibly failing) somewhere. 
    - The detection logic is relatively complex especially if it involves each one of the 3 resources mentioned as opposed to e.g. only the namespace or the `Cluster` resource.
* A "special" `Shoot` resource with a name different from the original one (as that one may still exist), created by copying the original one (including its status) and marking it as "leftover" somehow (via a label, annotation, or a new field). The main disadvantages of this approach are:
    - It has the potential of creating a lot of confusion between "normal" shoots and "leftover" shoots for the user. Special care should be taken that "leftover" shoots are distinguished from "normal" ones in the dashboard, `kubectl` queries, etc. 
    - Implementation could be easier on one side, since "cleanup" could be implemented as a new `Shoot` operation. On the other side, the relatively heavyweight machinery used in the shoot controller (`Botanist` etc.) would require adaptation to be applied to this special case, so all other operations would also be affected by the change. Many of the steps to properly initialize this machinery would not be really needed in this case, however they would still be executed (and so may fail).
    - It should be ensured that "leftover" shoots are never reconciled by the "normal" shoot controller, as this may have rather disastrous effect on existing shoots.
    - Purely conceptually, it overloads the existing `Shoot` resource with new semantics that could be better captured  by introducing a new resource kind.
* A new resource kind created especially for this purpose that contains only the relevant details for performing the cleanup operation, e.g. `ShootLeftover`. While this approach avoids the disadvantages of the other two, it comes at the price of introducing a new resource (albeit a relatively simple one), together with its boilerplate API server code and maintenance cost associated with graduating to new versions, etc.

**Comment by stoyanr** [comment]
From the above approaches, I personally tend to favor the 3rd one (new resource kind). I consider it the most straightforward of the three, as it can be designed and implemented independently of the shoot controller by focusing only on the details relevant for implementing the cleanup properly, without affecting any existing implementation or logic. It is also the most flexible one, as it does not depend on any of the leftover resources actually being there. Even if the `Shoot` is long gone and its `Cluster` resource as well (so basically its impossible to recover the original `Shoot`), it would still be possible to create (and then delete) a `ShootLeftover` to get rid of e.g. an almost empty shoot namespace, while properly reporting any progress and errors in the resource status.

I already started exploring this approach in #5150.

Please share your feedback / thoughts on this topic.
/cc @timebertt @plkokanov @rfranzke @timuthy

**Comment by vlerenc** [comment]
Gut feeling would have been rather option #1 (no additional resource in the garden cluster). This feels, at least to me, more "encapsulated" (this topic concerns only the seed, so the seed should care and only the seed). The (old) seed cluster's job is to get rid of "stuff" that doesn't belong there. That's it's job, whether it's a deleted or migrated shoot. It contains "stuff", but the shoot is gone or this seed/gardenlet is not responsible anymore? OK, off that "stuff" goes to /dev/null. If that fails, which can happen also for regular cluster deletion, we raise an alert. We have other critical incidents where we raise alerts, e.g. failed backups. I know, that's not great because there is alert fatigue, but the line of argument is rather: 1.) we don't report all things that can go wrong back to the garden cluster either and 2.) even if there is an additional resource, nobody will check probably and both, these resources as well as alerts can be checked. But the main reason is, gut feeling, that we might want to contain/limit the issue to the seed that should be able to drive the subject matter autonomously, thereby reducing hopefully complexity (or not adding more). WDYT?

**Comment by stoyanr** [comment]
@vlerenc To your points: Even if we agree that "the topic concerns only the seed", it doesn't help with the above drawbacks. It will be hard to get visibility that something is happening or needs to happen, and what's the progress and any errors, and firing alerts for errors during cleanup seems a bit too much to me. With an additional resource, you can do e.g. `k get slo -A` and immediately see if there is anything that requires attention (`ShootLevtover` resources are short-lived, they are usually immediately deleted after creation so that the cleanup process could be executed, and after it's finished they are gone). You can then optionally build upon this more visibility if required (dashboard pages, grafana dashboards, etc.).

**Comment by rfranzke** [comment]
Thanks for the summary and pointing out the drawbacks 👍🏻 Reading all this, I tend towards option 3 as well, even though I initially had some mixed feelings about this `ShootLeftover` resource. Though, I don't have a better proposal at hand. Relying on the `Cluster` in the seed is a great idea, but the operation's status would indeed be intransparent and I never was a fan of only relying on alerts (given that there are so many false positives). 

> even if there is an additional resource, nobody will check probably

Let's rather fix this then. We have a similar behaviour already today with `BackupEntry`s. They can remain after `Shoot` deletion for some time, and if something goes wrong then it is reported in the `status`. Operators should check or it should at least become easier to get information about such problems (Dashboard/gardenctl commands). With a `ShootLeftover` resource it would be quite similar.

**Comment by vlerenc** [comment]
Hmm... I cannot agree with either of you, but that's OK.

Let me just add the following general thoughts:
- I am not arguing for alerts as solution, just as mitigation that is cheaper than an extra resource.
- I am generally not of the opinion we should create "planned work" for operators. That's just like "planned downtime". It should not be the case.
- We should strive for automation and instead of investing into the transport of the information why something failed in cleanup, invest in said cleanup.
- We should all try to keep complexity low. Encapsulation, low coupling and high cohesion are the usual means to that goal. So, if some component has the job to do something, then it should do that autonomously. Only if the above/remote component needs to know, it shall share that information, but otherwise it shall not.

Having said that, that's my "engineering feeling/response" to that question and others may have other opinions. It's what I would have done: "keep the problem local to the seed where it belongs to", but I am not the one doing it, so I can understand if you reject that viewpoint.

**Comment by stoyanr** [comment]
@vlerenc I personally do subscribe to every of the general statements above, it's just that I am not sure how exactly to implement the first approach while avoiding the issues that I mentioned. 

Let me just point out that the existence of the extra resource doesn't mean that it has to be created manually in order for something to happen. For the "bad case" scenario, as part of the "fallback" the corresponding resource will be created (and immediately deleted to trigger the cleanup) automatically. And if it succeeds, everything will be cleaned up without the operator having to do anything it or even be aware that something is happening.

However, errors are possible and even likely (the migration failed and a force restore took place after all). I am currently testing the implementation and I am afraid that there are too many reasons why it could fail. From my perspective, making sure the errors are reported properly and made visible is a must. These errors are however not critical and therefore alerts would not be an appropriate approach.

**Comment by vlerenc** [comment]
@stoyanr If you want, we can talk out-of-band. Maybe I didn't get the problem entirely. It's about "controller detects the need for cleanup by detecting the leftover resources in the seed directly", so all happens in the seed, but the decision depends on the "tracking information" in the garden cluster. You listed:

1. Progress and errors are not reported in a status, and therefore harder to track and monitor, or even be aware that a cleanup is happening (and possibly failing) somewhere.

That is true and I have nothing to offer here. I accepted that as downside to keep complexity low.

I also cannot imagine that this is the only "progress and error information" that we then would not transport. There must be also other things we do not transport. Usually, one would try to solve that with resilient implementations that do not forget and retry.

> I am currently testing the implementation and I am afraid that there are too many reasons why it could fail

Uh, that's where I became unsure after reading your reply.
Which problems and failures to cleanup are we talking about?
Isn't that primarily/exclusively about cluster resources?
If not, then I may be on the wrong track here.

2. The detection logic is relatively complex especially if it involves each one of the 3 resources mentioned as opposed to e.g. only the namespace or the Cluster resource.

Why is that the case? Naively, I thought the `gardenlet` sees the `cluster` resource, but no `shoot` resource for that seed (because it was either deleted or migrated, which is probably the same because of the effects of the `SeedAuthoriser` that probably needs to be adapted for proposal (3), but not here) and then takes action. Deletes stuff and only when done, the `cluster` can go. Shouldn't that be rather less instead of more effort than additional resources?

Look, I do not want to propose more effort. I wanted to propose less effort. If I am wrong, then ignore my suggestion.

I was just of the opinion that as long as we do not lose sight of the cluster residue, e.g. because of the `cluster` resource that you mentioned in the description of (1) and an alert (that will be ignored of course, like additional resources in the garden cluster in my opinion, unless we find a way to aggregate and dispatch them to the alert owners, which I am trying to discuss with Istvan anyway) that this would be simpler/easier/less complex.

> Let me just point out that the existence of the extra resource doesn't mean that it has to be created manually in order for something to happen.

Yes, sure, that was understood.

**Comment by stoyanr** [comment]
@vlerenc Let's talk out-of-band. Just a few more comments:

> Usually, one would try to solve that with resilient implementations that do not forget and retry. ... Which problems and failures to cleanup are we talking about?

It will be just such an implementation. However, "resilient" doesn't mean "always expected to eventually succeed, no matter what the current shoot state may be". I will write more about when it should be expected to succeed, as this needs to be specified / clarified independent of the current discussion.

> Why is that the case?  ...

What you described is just one possible scenario. You may want to consider other cases, e.g. just a leftover backup entry, or just a cluster, or just a namespace without anything else. Some of these cases are not "normal" (they can only be achieved via manual actions or bugs in our components), and still the cleanup controller *may* be able to help for some of them.

Also consider that we should perhaps introduce a "grace period" after a fallback before the leftovers in the source seed are actually deleted, since without it they will be gone before the source seed has the chance to create the so-called "final full snapshot" (this is not critical, as the forced restoration will proceed without it after a timeout anyway, but this way it's slower and may result in data loss). This would be trivial to introduce with a resource (the controller will compare the resource deletion timestamp against the grace period to determine when to take action), and I am not even sure how to do it properly without a resource.

**Comment by stoyanr** [comment]
I would like to document my assumptions of when the new controller (independently if there is a new resource or not) should be expected to successfully cleanup the shoot leftover resources. 

The controller should always be able to successfully cleanup the shoot leftover resources if the following conditions are met:

* The seed cluster is healthy, i.e. its `gardenlet`, `etcd-druid`, and all needed extensions are installed an operational.
* The shoot is in a state that can normally be reached by executing one of the available operations (creation, reconciliation, migration, restoration, and deletion). It can be failing in the middle of an operation, so "half-created", "half-migrated", etc. shoots should also be supported.

Conversely, the controller could not be expected to always be able to successfully cleanup shoot leftover resources (it *might* still work, but success is not guaranteed and hard to predict) if:
* The seed cluster is not healthy.
* The shoot is in a state that can't normally be reached by executing one of the available operations (either the shoot control plane was manually tampered with, or a bug in one of these operations led to the shoot being in a state that is not "normal").

In addition, under the above conditions, the controller should support shoots in different allowed states and feature gates, such as:

* Awake as well as hibernated shoots.
* Shoots created with `UseDNSRecords` enabled as well as disabled (the actual cleanup implementation should not itself depend on this feature gate).

/cc @vlerenc @rfranzke @timebertt You might want to check if the above assumptions are ok from your perspective.

**Comment by timebertt** [comment]
I still strongly prefer the first approach mentioned above: only rely on the `Cluster` resource for detection and don't report into the garden cluster.

This is because:
- We agreed that the cleanup mechanism should be a "best effort" mechanism that can help operators in cases we can foresee (currently that's only the forceful migration), but not in all cases. So let's not discuss cleanup of states that we cannot predict, especially ones caused by bugs. If we go down that road, we will never be finished, as we can never predict (and don't want to?) all possible bug scenarios.
- Focusing on cleanup after forceful migration: In this case, we definitely got aware about a problematic situation on the old seed, as we migrated shoots away from it. Hence, I don't think that reporting into the garden cluster is actually necessary (or a strong argument), because operators will have to look into the broken seed anyway and there will still be things to cleanup manually. Listing `Cluster`s or `Namespace`s labelled with a `cleanup` label (added after detecting and triggering the mechanism) is just as simple as listing another resource in the garden cluster.
- If something goes south and leftovers remain on the seed and block the cleanup, there will be logs and events (or even a status on the `Cluster` resource if you want). So it will be easy to check why they are orphaned. No need to report such errors into the garden.
- We consider the probably that such a cleanup is needed (e.g. forceful migration) to be quite low (at least currently). When looking at the complexity/effort/perfection of the solution (new resource, granular reporting, etc.), it simply feels like a huge overkill for the low probability and the nature of a "best effort cleanup". Comparing it to the effort of running a script against all orphaned namespaces on one seed, it just doesn't seem to be worth it.
- Triggering the cleanup by detecting orphaned `Namespace`/`Cluster` resources will work (almost) always. Even if there is no controller creating the leftover resource. By definition, such orphaned resources already represent the "leftover state". So no need to declare it again somewhere else (which could in turn be inconsistent again).
- That's also how kube controllers work. If there is a leftover resources created by the controller on behalft of an object that is gone now, they simply clean it up. Or the garbage collector kicks in. But this will be done somewhat silently without an extra resource to report to (at most some events), even though there are also quite some things that could go wrong.

However, if we learn that this mechanism is not enough and there is need for a fully-fledged cleanup mechanism with reporting to garden, etc. we can still introduce such a resource later on.
But I would definitely vote for sparing the complexity and effort for now.

**Comment by rfranzke** [comment]
Thanks for further opinions! I think there are many valid/reasonable points. As proposed and as a compromise for the time being, shall we go ahead with the less complex first approach for now and get our feet wet/get some experience? Introducing a dedicated resource in the Garden API can always be done later with (probably?) relatively manageable effort.

**Comment by stoyanr** [comment]
@timebertt Thanks for your feedback. Let me reiterate a few basic points:

* My intention is to propose a mechanism that works in general, not just for shoots that could not be migrated and had to be forcefully restored.
* If the problematic situation on the old seed is a persisting one, the cleanup should not be expected to work no matter how we implemented it, and we likely have a bigger problem than cleaning up leftover resources. I would not focus on this situation, I regard it as exceptional, and one that perhaps doesn't require cleanup at all, but more drastic measures.
* `Cluster` resources live the in the seed, and there are many seeds per landscape. Only resources in the garden cluster allow for easy visibility across seeds.
* `Cluster` resources are not the only leftover resources (there are also namespaces, backup entries, and DNS owners). Detecting all possible leftover resources in order to trigger the cleanup would increase the complexity considerably.
* Logs and events are not really "easy" as an indication that something is happening / failing and why, compared to a status of a resource, especially if they are associated with a seed resource. 
* The `Cluster` resource doesn't have a status and so far was not intended to be actively reconciled. Adding a status to this resource as an afterthought and reconciling it to perform cleanup would be hackish and confusing.
* We may need to control the way cleanup is performed, e.g. some cleanups need a grace period as I pointed out. With a resource this could easily be added and implemented properly. Without a resource we would need to rely on annotations on existing resources. I also consider this hackish compared to using a proper resource.
* I don't believe that garbage collection mechanims in Kubernetes could be used as an example for what we need to do here. I also don't think that if they needed anything similar, they would implement it by repurposing existing resources in ways they were not originally intended to be used.
* I actually looked into how the cleanup mechanism could be implemented using the `Cluster` resource and I really didn't like the implications, as it would be unlike any other controller have implemented so far. 

All in all, we may save the "complexity and effort" of introducing a new resource, but only at the expense of (in my opinion, worse) complexity and effort of properly detecting, controlling, and reporting the cleanup using existing resources, and at the price of using them in ways they were not intended to be used, achieving worse usability of the entire mechanism.

@rfranzke I am not even sure how to implement this "less complex first approach" properly at the moment, and the implementation of the controller using a dedicated resource is in a rather advanced stage, see #5150. I would propose to have a short sync to decide how to proceed.

**Comment by timebertt** [comment]
A few short replies to "defend my points":

> * `Cluster` resources are not the only leftover resources (there are also namespaces, backup entries, and DNS owners). Detecting all possible leftover resources in order to trigger the cleanup would increase the complexity considerably.

I think, my point was misunderstood. Let me try to rephrase it:
I would only use either the `Cluster` resource or the corresponding `Namespace` as a trigger for the cleanup mechanism. This would be equivalent to triggering the whole cleanup logic by deleting the `ShootLeftover` resource.

> * The `Cluster` resource doesn't have a status and so far was not intended to be actively reconciled. Adding a status to this resource as an afterthought and reconciling it to perform cleanup would be hackish and confusing.

The `Cluster` resource is still not supposed to be "reconciled". The shoot controller should simply watch it as one of the "owned objects" that it created. The object that the controller "reconciles" is still the shoot, and the fact that it's gone causes the leftovers to be cleaned up appropriately.

> * We may need to control the way cleanup is performed, e.g. some cleanups need a grace period as I pointed out. With a resource this could easily be added and implemented properly. Without a resource we would need to rely on annotations on existing resources. I also consider this hackish compared to using a proper resource.

We could simply add a deletion timestamp to the cluster resource (either in the future and only then cleanup or start cleanup once a grace period after the timestamp has elapsed). I wouldn't consider this hacky at all, as it uses the normal API machinery.

> I would propose to have a short sync to decide how to proceed.

+1

**Comment by stoyanr** [comment]
> We could simply add a deletion timestamp to the cluster resource 

This is not enough, we need to specify the actual grace period somewhere, either as a duration or as another timestamp (some cleanups do require a grace period, others don't)

> I would only use either the Cluster resource or the corresponding Namespace as a trigger for the cleanup mechanism

So if the resource that is used as a trigger is gone for whatever reason, nothing will happen, even if there are still other resources left.

> The Cluster resource is still not supposed to be "reconciled" ... 

So we will then be reconciling the shoot and reporting the cleanup progress / errors information to a status (and events) of a different resource, namely the `Cluster`. This is partly what I referred to as "unlike any other controller" above. I think there is a reason why controllers are usually not implemented like this.

**Comment by stoyanr** [comment]
In a discussion with @rfranzke, @timebertt, and @plkokanov we decided to adopt the "new resource" approach (the third one listed in https://github.com/gardener/gardener/issues/5173#issuecomment-995562573). The main arguments for this are:

* We regard this as a general mechanism that could also be used for "forceful deletion" of clusters (also called "purge" or "drop cluster", see https://github.com/gardener/gardener/issues/3110#issuecomment-738745082), in addition to the "forceful restoration" introduced with #5123.
* Although forceful restoration is expected to be rare, forceful deletion, if offered as an option to users, will be used much more often, and so the cleanup mechanism does require optimal visibility for progress and errors. Only resources in the garden cluster allow for easy visibility across seeds.

The other arguments listed in https://github.com/gardener/gardener/issues/5173#issuecomment-998582070 are also applicable, but not considered critical.

The provisional name for the new resource is `ShootLeftover`, although it could still be changed if there are better proposals. Since the resource stands as a "surrogate" for the (deleted or migrated) `Shoot`, it should contain `Shoot` in its name. As we are dealing with cleaning-up of "leftover" or "orphaned" resources in the seed, `ShootLeftover` is perhaps as good as any other name.

The first implementation proposed with #5150 will only be tested for fully-reconciled and "half-migrated" shoots, so it could be used with "forcefully restored" shoots. This is also the simpler case, as it does not require any infrastructure to be actually deleted, since it's still in use by the shoot. Later on the implementation could be adapted for the "forceful deletion" case.

**Comment by vlerenc** [comment]
OK, what's the status here? It seems, @timebertt (initially) and myself would rather pick option #1 with less effort while @stoyanr and @rfranzke (and then possibly also @timebertt) would like to pick option #3 with a way to report issues back into the garden cluster.

Whatever we plan to do, we should do it and close CPM (actually, this also covers forceful deletion and not only CPM).

If nobody can take the decision, I will: Clearly option #1. Reasoning above. We must trust our code and cannot add artificial resources for everything that can go wrong - we must make sure our controllers fix the state. Also, I doubt option #3 will be implemented by anyone anytime soon, so it's unrealistic anyway and we cannot keep this issue open forever.

**Comment by plkokanov** [comment]
Closing this in favour of #6302
